export const storeKeys = {
  SIT_HEIGHT: 'SIT_HEIGHT',
  STAND_HEIGHT: 'STAND_HEIGHT',
  LOWEST_HEIGHT: 'LOWEST_HEIGHT',
  DESK_OFFSET_HEIGHT: 'DESK_OFFSET_HEIGHT',
  DESK_ADDRESS: 'DESK_ADDRESS',
};
